apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.178.41:5000/backend:latest
        imagePullPolicy: Always
        env:
        - name: BACKEND_PORT
          value: "8000"
        command: ["./backend"]
        ports:
        - containerPort: 8000 