apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 192.168.178.41:5000/frontend:latest
        imagePullPolicy: Always
        env:
        - name: FRONTEND_PORT
          value: "8000"
        ports:
        - containerPort: 8000 